### ISSUE TITLE
JS not compiling to output folder

### ISSUE THREAD

**Issue by elduderino3000** [Prototype-Group/generator-prototype#37]
When fist running grunt server when making an edit my JS files in "resources/js/" the watch task is not detecting any of the changes and the files are not being compiled to the " _output" directory. Everything else (scss/templates) is compiling correctly on watch. I have to run grunt build to get the files JS folder/files to compile to the  " _output" folder. The the grunt watch starts detecting the JS file edits but I am receiving the following error and the JS does not get synced to the " _output" folder.

Grunt watch error:
"jit-grunt: Plugin for the "js" task not found.
If you have installed the plugin already, please setting the static mapping.
See https://github.com/shootaroo/jit-grunt#static-mappings

Warning: Task "js" failed."

**Comment by Sebastian-Fitzner** [comment]
Can you tell me, which modules you have chosen? You can post your yo-rc.json, if you want...

**Comment by ldexterldesign** [comment]
+1

**Comment by elduderino3000** [comment]
yo-rc.json:

{
  "generator-prototype": {
    "projectName": "Test",
    "projectAuthor": "",
    "installAssemble": true,
    "installPlugin": true,
    "modules": [
      "grunt-autoprefixer",
      "grunt-browser-sync",
      "grunt-combine-mq",
      "grunt-contrib-uglify",
      "grunt-modernizr",
      "grunt-version"
    ],
    "features": [
      "sassInsteadOfCompass",
      "installExtendedLayout",
      "createDevFolder",
      "installDocs"
    ],
    "jsLibs": [
      "jquery",
      "requirejs"
    ],
    "cssLibs": [
      "neat"
    ],
    "pgPackages": [
      "pgMethodology",
      "pgSCSS",
      "pgJS"
    ],
    "installProxy": false,
    "proxyHost": "0.0.0.0 ",
    "proxyPort": 80,
    "author": {
      "name": "",
      "login": "",
      "email": ""
    },
    "plugin": [
      "assemble-contrib-permalinks",
      "assemble-contrib-sitemap",
      "assemble-related-pages"
    ]
  }
}

**Comment by Sebastian-Fitzner** [comment]
@elduderino3000 you detected a bug. To fix this in your project, just at the following lines to your `Gruntfile.js`:

``` js 
grunt.registerTask('js', [
	'sync:js'
]);
```

I going to fix this in a few minutes in the generator... Thank you for posting this.

**Comment by Sebastian-Fitzner** [comment]
hmm, I scaffolded the project with your settings, but have no problems with the js folder and the watch task. It works like expected. 

Please post your Gruntfile.js and your watch task ...

**Comment by Sebastian-Fitzner** [comment]
Seems to be solved?! If not, you can reopen the issue...
