### ISSUE TITLE
Windows 7 node 0.12.* node-sass/grunt-sass Problem

### ISSUE THREAD

**Issue by webdesignberlin** [Prototype-Group/generator-prototype#38]
Hi,

after update node to version 0.12.* grunt-sass doesnt work with version grunt-sass "~0.16.0", cause it depends an old node-sass version. after updating grunt-sass to version 0.18.1 it works fine.

**Comment by Sebastian-Fitzner** [comment]
Hi,

thanks for the hint. With the next major release this issue will be addressed. Because the next major release will support Gulp you have to wait til next week.

**Comment by Sebastian-Fitzner** [comment]
Fixed with minor release ...
