### ISSUE TITLE
TypeError: Cannot read property 'read' of undefined

### ISSUE THREAD

**Issue by johnnybridges** [Prototype-Group/generator-prototype#39]
Unsure if this is just my local setup, but since upgrading Node/NPM, I'm receiving a weird bug when trying to run the latest `generator-prototype@0.5.9`. This could also be an issue with Yeoman etc, but other generators are still working which is why I'm a bit confused.

Node Version: `v0.12.2`
NPM Version: `2.7.4`
Yeoman Version: `1.4.6`

Output when trying to run generator: 
```zsh
$ yo prototype
(!) #src() and #dest() are deprecated. Please read the documentation to learn about
the new ways of handling files. http://yeoman.io/authoring/file-system.html
events.js:85
      throw er; // Unhandled 'error' event
            ^
TypeError: Cannot read property 'read' of undefined
    at module.exports.yeoman.generators.Base.extend.initializing (/usr/local/lib/node_modules/generator-prototype/generators/app/index.js:13:26)
    at /usr/local/lib/node_modules/generator-prototype/node_modules/yeoman-generator/lib/base.js:412:16
    at processImmediate [as _immediateCallback] (timers.js:358:17)
```

Please let me know if you need any other info, or if I'm being an idiot!

Cheers :smile:

**Comment by Sebastian-Fitzner** [comment]
Hi, 

I can reproduce the error with the newest yeoman version. Unfortunately they changed specific file methods in 1.4.6 ... I will update the generator asap. Thx for the hint. 

Greetz

**Comment by wihodges** [comment]
+1 Same problem here.

**Comment by Sebastian-Fitzner** [comment]
Hi,

first of all, issue is fixed!

The problem is the new yeoman-generator version (0.18.0). This version contains some major changes: 

- file system handling
- underscore dependency
- `.template()` fn should be replaced with `this.fs.copyTpl()`

For more details, see:
- https://github.com/yeoman/generator/issues/766 
- http://yeoman.io/blog/release-0.18.html

**Comment by johnnybridges** [comment]
<3 thank you so much!
