### ISSUE TITLE
Review yo generator

### ISSUE THREAD

**Issue by ldexterldesign** [Prototype-Group/generator-prototype#43]
Hey,

There appears to be some documentation inconsistencies between http://yeoman.io/generators/ and http://www.prototype-generator.com/getting-started/plugins-and-modules.html:

1. grunt-accessibility
2. grunt-responsive-images
3. grunt-sass

<img width="1440" alt="screen shot 2015-08-16 at 20 05 04" src="https://cloud.githubusercontent.com/assets/1715809/9294880/41642d5a-4452-11e5-9b65-b64badea5e68.png">

Hope it's useful

Regards

**Comment by Sebastian-Fitzner** [comment]
That is right and will be fixed ... The documentation will be updated when I release the next version of the generator.

Thx for your support.

**Comment by ldexterldesign** [comment]
Kind thanks

**Comment by Sebastian-Fitzner** [comment]
in the next week I want to publish the new website of veams. So this is considered ...
